### ISSUE TITLE
question about week 9 notes

### ISSUE THREAD

**Issue by schester1** [ldeo-glaciology/ice-sheet-seminar-2022#13]
two quick math-related questions: 1) when we differentiate the equation for mean normal stress, why isn't it with respect to x on both sides of the equation? 

$$
\frac{\partial \sigma_{m}}{\partial x} =- \rho g \frac{\partial H}{\partial z}
$$

2) when we integrate vertically, why is the limit on the left 0 to u not 0 to H?

$$
\int^u_0 du = 2A \left(\rho g \alpha H \right)^n \int^z_0\left(1-\frac{z}{H}\right)^n dz.
$$

**Comment by jkingslake** [comment]
Hi @schester1, thanks for the questions. 

1. This is a typo! Good spot! It should be $\frac{\partial H}{\partial x}$
PR https://github.com/ldeo-glaciology/ice-sheet-seminar-2022/pull/14 corrects this.

2. This integral is not across the whole thickness of the ice sheet, it is only from the bed to some height $z$, so the value of the horizontal velocity at that height is $u$. To put it another way, you can think of the integral on the left as actually being evaluated many times (an infinite number of times, really!) at many different values of $z$. For every value of $z$, you get a different value of $u$, given by the function on the left. 

Let me know if this makes sense.

If this is still confusing, let's discuss in class this week.
